### ISSUE TITLE
Update to recent version

### ISSUE THREAD

**Issue by leonard84** [cyber-dojo-languages/groovy-spock#1]
Hi @JonJagger,

I noticed that the image uses a quite outdated version of Java (13), Groovy (3.0.3), and Spock (2.0) would it be possible to update them to.

* Java 17
* Groovy 4
* Spock 2.3-groovy-4.0

**Comment by JonJagger** [comment]
Hi Leonard
on the todo list.
Thanks
Jon

**Comment by JonJagger** [comment]
Hi Leonard,
Groovy now at 4.0.9
Spock now at 2.4
Many thanks for your interest in cyber-dojo :-)
